magland/mountainlab

- devtools/compile_all.sh
I think it's easier to just run one script
@magland ?
> script to run all other compile_ scripts

- mountainsort/src/mountainsort.pro
- mountainview/src/mountainview.pro
- spikespy/src/spikespy.pro
Okay, so here's an example where I had already modified these .pro files. So when I added the new changes in the bug fix branch we can also see those changes. But if we accept this pull request without me pushing those other changes, the thing won't compile.
I guess that's why I should always be working in a non-master branch, right?
*learning curve*
> fix mac compilation

- mountainsort/src/mountainsort.pro
- mountainsort/src/unit_tests/testMain.cpp
- mountainsort/src/unit_tests/testMda.cpp
- mountainsort/src/unit_tests/testMda.h
A stub code for mda unit tests. I will be adding more stuff later.
I will also create a script to compile & run all unit tests with single command in devtools.
For now it can be run with `qmake -config test && make check`
@magland
> basic files and .pro file update for unit tests

- devtools/run_all_tests.sh
- mountainsort/src/mda/diskwritemda.cpp
- mountainsort/src/unit_tests/testMda.cpp
- mountainsort/src/unit_tests/testMda.h
> script to run tests, added simple benchmarks to mda test

- compile_mountainbrowser.sh
- compile_mountainsort.sh
- compile_mountainview.sh
- compile_server.sh
- compile_spikespy.sh
- devtools/compile_all.sh
`compile_all.sh` should stop on compile error and print the name of the last executed script
@magland
> updated build scripts

- mountainsort/src/mda/mdaio.cpp
> removed read macros from mdaio

- matlab/processing/mscmd_fit_stage.m
- mountainsort/src/processors/fit_stage.cpp
- mountainsort/src/processors/fit_stage.h
- mountainsort/src/processors/fit_stage_new.cpp
- mountainsort/src/processors/fit_stage_processor.cpp
old version loaded entire file into memory. Now, when using --use_old=0 it calls fit_stage_new.cpp which does the file chunking and parallel threads.
> implement parallel and disk/chunk version of fit stage

- mountainsort/src/mda/mdaio.cpp
- mountainsort/src/mda/mdaio.h
- mountainsort/src/mountainsort.pro
- mountainsort/src/unit_tests/testMain.cpp
- mountainsort/src/unit_tests/testMdaIO.cpp
- mountainsort/src/unit_tests/testMdaIO.h
> tests for mdaio

- matlab/processing/ms_merge_across_channels.m
- matlab/processing/mscmd_merge_across_channels.m
- mountainsort/src/core/msprocessmanager.cpp
- mountainsort/src/isosplit/isosplit2.cpp
- mountainsort/src/isosplit/isosplit2.h
- mountainsort/src/mountainsort.pro
- mountainsort/src/mountainsortmain.cpp
- mountainsort/src/processors/merge_across_channels.cpp
- mountainsort/src/processors/merge_across_channels.h
- mountainsort/src/processors/merge_across_channels_processor.cpp
- mountainsort/src/processors/merge_across_channels_processor.h
Implemented mscmd_merge_across_channels
> Jfm merge across channels

- mountainsort/src/processors/fit_stage_new.cpp
check to see if tt is in correct range -- rounding issue
> fix crash bug in fit_stage_new

- mountainsort/src/processors/fit_stage_new.cpp
Because I thought it was a multithread openmp issue. But it wasn't. It's just the thing only crashed when using multiple threads, for some reason.
> fix crash bug, took me all day to find. :(

- common/mda/mda.cpp
- common/mda/mda.h
- mountainsort/src/unit_tests/testMda.cpp
- mountainsort/src/unit_tests/testMda.h
- tests for constructors
- tests for set / get functions
- simple benchmark for set / get
- corrected `const` in one method signature
@magland 
Let me know if you'd like to see unit tests or benchmarks for some specific functionality. Otherwise I'm done with this issue and would like to move on to some other tasks (preferably assigned by you in jira :) ).
> more tests for Mda

- common/mda/remotereadmda.cpp
- mountainsort/src/mountainsort.pro
- mountainview/src/computationthread.cpp
- mountainview/src/computationthread.h
- mountainview/src/flowlayout.cpp
- mountainview/src/flowlayout.h
- mountainview/src/mountainview.pro
- mountainview/src/mountainviewmain.cpp
- mountainview/src/mvclusterdetailwidget.cpp
- mountainview/src/mvclusterdetailwidget.h
- mountainview/src/mvcontrolpanel.cpp
- mountainview/src/mvcontrolpanel.h
- mountainview/src/mvcrosscorrelogramswidget2.cpp
- mountainview/src/mvcrosscorrelogramswidget2.h
- mountainview/src/mvoverview2widget.cpp
- mountainview/src/mvoverview2widget.h
- mountainview/src/run_mountainview_script.cpp
- mountainview/src/taskprogress.cpp
- mountainview/src/taskprogress.h
- mountainview/src/taskprogressview.cpp
rewriting of mountainview control panel
fixing and improving taskprogress
taskprogressview: show errors in red
serious bug fix in remote mda!! (effects the end part of a remote array)
> Mountainview dev

- mountainsort/src/processors/bandpass_filter0.cpp
- mountainsort/src/processors/bandpass_filter0.h
- mountainsort/src/processors/bandpass_filter_processor.cpp
Chunk size can be passed as optional processor parameter.
@magland
> possibility to override processing chunk size in bandpass filter

- mountainsort/src/processors/mv_discrimhist.cpp
- mountainsort/src/processors/mv_discrimhist.h
- mountainsort/src/processors/mv_discrimhist_processor.cpp
> mv_discrimhist_Processor has clip_size as optional parameter

- mountainview/src/core/actionfactory.cpp
- mountainview/src/core/actionfactory.h
- mountainview/src/mountainview.pro
- mountainview/src/views/mvclipswidget.cpp
- mountainview/src/views/mvclusterdetailwidget.cpp
- mountainview/src/views/mvtimeseriesviewbase.cpp
also removes code duplication related to creating QActions
@magland
> added zoom in/out actions to clips widget

- mountainprocess/src/mountainprocessmain.cpp
- mountainprocess/src/mpdaemon.cpp
Replaces https://github.com/magland/mountainlab/pull/106
> ML-147 rebased to current master

- mountainview/src/core/mvcontext.cpp
- mountainview/src/core/mvcontext.h
- mountainview/src/views/mvspikespraypanel.cpp
- mountainview/src/views/mvspikespraypanel.h
I have refactored MVSpikeSprayPanel and associated classes. I decoupled functionality from the widget class and improved user interface responsiveness. I also added small features such as displaying loading and rendering progress.
Before merging please have a look if I didn't mess up the calculations. I think they are okay but it's better if you have a look.
> Redesign of MVSpikeSprayPanel

- mountainview/src/views/mvclusterwidget.cpp
> use qobject_cast for sender()

- WIP/mountainbrowser/src/html/mbstudyview.html
- WIP/mountainbrowser/src/mbcontroller.cpp
- WIP/mountainbrowser/src/mbcontroller.h
- WIP/mountainbrowser/src/mountainbrowser.pro
- WIP/mountainbrowser/src/mountainbrowser.qrc
- WIP/mountainbrowser/src/mountainbrowsermain.cpp
- WIP/mountainbrowser/src/mountainbrowsermain.h
- mountainbrowser/src/html/qwebchannel.js
I know we're not using mountainbrowser anymore but it doesn't mean we shouldn't integrate this patch.
> Make mountainbrowser build and work against Qt 5.6

- mlcommon/include/mda/mdareader.h
- mlcommon/include/mda/mdareader_p.h
- mlcommon/src/mda/mdareader.cpp
- mlcommon/src/mda/remotereadmda.cpp
- mlcommon/src/mlcommon.pro
- tests/auto/MdaReader/MdaReader.pro
- tests/auto/MdaReader/tst_mdareadertest.cpp
It currently doesn't do anything useful but I'd like to merge it into master so that I can safely work on it without having to rebase it every week.
> Mdareaderwriter

- packages/mountainsort2/src/p_isolation_metrics.cpp
> changed to float type for qmax inarg of p_iso metrics in ms2 pckg

- cpp/mlcommon/include/tracing/tracing.h
- cpp/mlcommon/src/mlcommon.pro
- cpp/mlcommon/src/tracing/tracing.cpp
The tracing system utilizing chrome://tracing. Tracing code not actually deployed anywhere so no regressions expected.
> The performance tracing system
